#!/usr/bin/env python3
"""Collect delivery data from the current git repository as JSON.

Uses the GitHub CLI (`gh`) for pull requests, reviews, and releases when it is
installed and authenticated; otherwise falls back to local git history only
(squash-merge commits ending in "(#N)", merge commits, and tags). Standard
library only, so it runs anywhere Python 3.8+ does.

Usage:
    python3 collect.py [--since YYYY-MM-DD] [--until YYYY-MM-DD] [--author LOGIN]
"""

import argparse
import json
import re
import shutil
import statistics
import subprocess
import sys
from datetime import datetime, timedelta, timezone

CONVENTIONAL_RE = re.compile(r"^(\w+)(\([^)]*\))?(!)?:")
MARKER_RE = re.compile(r"Generated by the ([a-z0-9-]+) skill on (\d{4}-\d{2}-\d{2})")
PR_SUFFIX_RE = re.compile(r"\(#(\d+)\)\s*$")
RELEASE_TITLE_RE = re.compile(r"^chore(\([^)]*\))?: release ")


def run(cmd, check=True):
    result = subprocess.run(cmd, capture_output=True, text=True)
    if check and result.returncode != 0:
        raise RuntimeError(f"{' '.join(cmd)} failed: {result.stderr.strip()}")
    return result.stdout


def parse_ts(value):
    if not value:
        return None
    return datetime.fromisoformat(value.replace("Z", "+00:00"))


def hours_between(start, end):
    if not start or not end:
        return None
    return round((end - start).total_seconds() / 3600, 2)


def commit_type(title):
    match = CONVENTIONAL_RE.match(title or "")
    return match.group(1).lower() if match else "other"


def is_bot(login, title):
    login = (login or "").lower()
    return (
        login.startswith("app/")
        or login.endswith("[bot]")
        or login in {"github-actions", "dependabot", "renovate"}
        or bool(RELEASE_TITLE_RE.match(title or ""))
    )


def percentile(values, pct):
    if not values:
        return None
    ordered = sorted(values)
    index = max(0, min(len(ordered) - 1, round(pct / 100 * (len(ordered) - 1))))
    return ordered[index]


def summarize(values):
    values = [v for v in values if v is not None]
    if not values:
        return {"n": 0, "median": None, "p90": None}
    return {
        "n": len(values),
        "median": round(statistics.median(values), 2),
        "p90": round(percentile(values, 90), 2),
    }


def gh_available():
    if not shutil.which("gh"):
        return False
    return subprocess.run(["gh", "auth", "status"], capture_output=True).returncode == 0


def collect_prs_gh():
    fields = "number,title,author,createdAt,mergedAt,additions,deletions,changedFiles,files,reviews"
    raw = run(["gh", "pr", "list", "--state", "merged", "--limit", "1000", "--json", fields])
    prs = []
    for pr in json.loads(raw):
        login = (pr.get("author") or {}).get("login")
        created, merged = parse_ts(pr["createdAt"]), parse_ts(pr["mergedAt"])
        reviews = [
            {"author": (r.get("author") or {}).get("login"), "submitted_at": r.get("submittedAt")}
            for r in pr.get("reviews") or []
            if r.get("submittedAt")
        ]
        other_reviews = [parse_ts(r["submitted_at"]) for r in reviews if r["author"] != login]
        first_review = min(other_reviews) if other_reviews else None
        prs.append({
            "number": pr["number"],
            "title": pr["title"],
            "author": login,
            "is_bot": is_bot(login, pr["title"]),
            "type": commit_type(pr["title"]),
            "created_at": pr["createdAt"],
            "merged_at": pr["mergedAt"],
            "cycle_hours": hours_between(created, merged),
            "first_review_hours": hours_between(created, first_review),
            "size": (pr.get("additions") or 0) + (pr.get("deletions") or 0),
            "files": [f["path"] for f in pr.get("files") or []],
            "reviews": reviews,
        })
    # The squash/merge commit on HEAD carries the PR author's git identity; fetching
    # commit authors through the GraphQL API instead hits node limits on big repos.
    identities = {p["number"]: p["git_identities"] for p in collect_prs_git(with_files=False)}
    for pr in prs:
        pr["git_identities"] = identities.get(pr["number"], [])
    return prs


def collect_prs_git(with_files=False):
    """Fallback: one entry per squash/merge commit on HEAD. No open time, so no cycle time."""
    raw = run(["git", "log", "--first-parent", "--format=%H%x1f%ae%x1f%an%x1f%aI%x1f%s"])
    prs = []
    for line in raw.splitlines():
        sha, author, name, date, subject = line.split("\x1f", 4)
        match = PR_SUFFIX_RE.search(subject) or re.search(r"Merge pull request #(\d+)", subject)
        if not match:
            continue
        title = PR_SUFFIX_RE.sub("", subject).strip()
        files = run(["git", "show", "--name-only", "--format=", sha]).split() if with_files else []
        prs.append({
            "number": int(match.group(1)),
            "title": title,
            "author": author,
            "is_bot": is_bot(author, title),
            "type": commit_type(title),
            "created_at": None,
            "merged_at": date,
            "cycle_hours": None,
            "first_review_hours": None,
            "size": None,
            "files": files,
            "reviews": [],
            "git_identities": [(name, author)],
        })
    return prs


def mailmap(name, email):
    """Canonical (name, email) per the repo's .mailmap, if any."""
    out = run(["git", "check-mailmap", f"{name} <{email}>"], check=False).strip()
    match = re.match(r"^(.*?)\s*<(.*)>$", out)
    return (match.group(1), match.group(2)) if match else (name, email)


def mailmap_lines(canonical, group, seen):
    """Exact .mailmap lines that would make a name-based merge explicit."""
    def top(author):
        tally = seen.get(author) or {}
        return max(tally, key=tally.get) if tally else None

    target = top(canonical)
    if not target or not target[1]:
        return []
    lines = []
    for author in sorted(group):
        for name, email in sorted(seen.get(author) or {}):
            if email and email.lower() != target[1].lower():
                lines.append(f"{target[0]} <{target[1]}> {name} <{email}>")
    return sorted(set(lines))


def group_identities(prs):
    """Merge author keys (logins, or emails in git-only mode) that belong to one person.

    Two keys merge when their commits share a git author email or a git author name
    (case-insensitive), after applying .mailmap. Returns {author_key: person} and the
    merged groups with the evidence that linked them, so the report can state the
    assumption instead of hiding it.
    """
    parent = {}

    def find(x):
        parent.setdefault(x, x)
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    token_owner, evidence = {}, {}
    for pr in prs:
        if pr["is_bot"] or not pr["author"]:
            continue
        key = f"author:{pr['author']}"
        find(key)
        for name, email in pr.get("git_identities") or []:
            name, email = mailmap(name, email)
            for token in (f"name:{name.strip().lower()}" if name.strip() else None,
                          f"email:{email.strip().lower()}" if email.strip() else None):
                if not token:
                    continue
                if token in token_owner and find(token_owner[token]) != find(key):
                    evidence.setdefault(frozenset((token_owner[token], key)), token)
                    parent[find(key)] = find(token_owner[token])
                token_owner.setdefault(token, key)

    counts, seen = {}, {}
    for pr in prs:
        if not pr["is_bot"] and pr["author"]:
            counts[pr["author"]] = counts.get(pr["author"], 0) + 1
            for identity in pr.get("git_identities") or []:
                tally = seen.setdefault(pr["author"], {})
                tally[tuple(identity)] = tally.get(tuple(identity), 0) + 1
    members = {}
    for author in counts:
        members.setdefault(find(f"author:{author}"), []).append(author)
    mapping, groups = {}, []
    for group in members.values():
        canonical = max(group, key=lambda a: (counts[a], a))
        for author in group:
            mapping[author] = canonical
        if len(group) > 1:
            linked_by = sorted({t for pair, t in evidence.items() if any(p[7:] in group for p in pair)})
            groups.append({
                "person": canonical,
                "accounts": sorted(group),
                "linked_by": linked_by,
                "suggested_mailmap": mailmap_lines(canonical, group, seen),
            })
    return mapping, groups


def collect_releases(use_gh):
    if use_gh:
        raw = run(["gh", "release", "list", "--limit", "200", "--json", "tagName,publishedAt"], check=False)
        if raw.strip():
            return [{"tag": r["tagName"], "date": r["publishedAt"]} for r in json.loads(raw)]
    raw = run(["git", "for-each-ref", "--sort=creatordate", "--format=%(refname:short)%1f%(creatordate:iso-strict)", "refs/tags"])
    return [dict(zip(("tag", "date"), line.split("\x1f"))) for line in raw.splitlines() if line]


def collect_reverts():
    raw = run(["git", "log", "--format=%H%x1f%aI%x1f%s", "--grep=^Revert", "-i"])
    return [dict(zip(("sha", "date", "subject"), line.split("\x1f", 2))) for line in raw.splitlines() if line]


def collect_skill_artifacts():
    """Tracked files carrying the shared 'Generated by the <skill> skill on <date>' header."""
    raw = run(["git", "grep", "-l", "-E", r"Generated by the [a-z0-9-]+ skill on [0-9]{4}-"], check=False)
    artifacts = []
    for path in raw.splitlines():
        with open(path, encoding="utf-8", errors="replace") as handle:
            match = MARKER_RE.search(handle.read())
        if not match:
            continue
        added = run(["git", "log", "--diff-filter=A", "--format=%aI", "--", path]).split()
        artifacts.append({
            "path": path,
            "skill": match.group(1),
            "marker_date": match.group(2),
            "committed_at": added[-1] if added else None,
        })
    return sorted(artifacts, key=lambda a: a["committed_at"] or a["marker_date"])


def invoking_user(use_gh):
    login = run(["gh", "api", "user", "--jq", ".login"], check=False).strip() if use_gh else ""
    return {
        "github_login": login or None,
        "git_name": run(["git", "config", "user.name"], check=False).strip() or None,
        "git_email": run(["git", "config", "user.email"], check=False).strip() or None,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--since", help="window start, YYYY-MM-DD (default: 90 days ago)")
    parser.add_argument("--until", help="window end, YYYY-MM-DD (default: now)")
    parser.add_argument("--author", help="login/name for the individual summary (default: invoking user)")
    parser.add_argument("--no-gh", action="store_true", help="force the git-only fallback")
    parser.add_argument("--no-merge-identities", action="store_true",
                        help="treat every login/email as a separate person")
    args = parser.parse_args()

    now = datetime.now(timezone.utc)
    until = parse_ts(args.until + "T23:59:59+00:00") if args.until else now
    since = parse_ts(args.since + "T00:00:00+00:00") if args.since else until - timedelta(days=90)

    if run(["git", "rev-parse", "--is-inside-work-tree"], check=False).strip() != "true":
        sys.exit("collect.py: run this inside a git repository")

    use_gh = not args.no_gh and gh_available()
    prs = collect_prs_gh() if use_gh else collect_prs_git(with_files=True)
    for pr in prs:
        merged = parse_ts(pr["merged_at"])
        pr["in_window"] = bool(merged and since <= merged <= until)

    mapping, identity_groups = ({}, []) if args.no_merge_identities else group_identities(prs)
    person = lambda key: mapping.get(key, key)
    for pr in prs:
        pr["person"] = person(pr["author"])
        for review in pr["reviews"]:
            review["person"] = person(review["author"])

    user = invoking_user(use_gh)
    # git-only mode identifies authors by email, since squash commits carry no login
    subject_key = args.author or user["github_login"] or user["git_email"]
    subject_key = next((a for a in mapping if a.lower() == (subject_key or "").lower()), subject_key)
    subject = person(subject_key)
    subject_accounts = sorted(a for a in mapping if mapping[a] == subject) or [subject_key]
    human_window = [p for p in prs if p["in_window"] and not p["is_bot"]]
    mine = [p for p in human_window if p["person"] == subject]
    weeks = max((until - since).days / 7, 1)
    releases = collect_releases(use_gh)

    output = {
        "repo": run(["git", "rev-parse", "--show-toplevel"]).strip().rsplit("/", 1)[-1],
        "source": "gh" if use_gh else "git-only",
        "window": {"since": since.date().isoformat(), "until": until.date().isoformat(), "weeks": round(weeks, 1)},
        "invoking_user": user,
        "identity_groups": identity_groups,
        "summary": {
            "merged_prs_in_window": len(human_window),
            "bot_prs_excluded": sum(1 for p in prs if p["in_window"] and p["is_bot"]),
            "merged_prs_per_week": round(len(human_window) / weeks, 2),
            "cycle_hours": summarize([p["cycle_hours"] for p in human_window]),
            "first_review_hours": summarize([p["first_review_hours"] for p in human_window]),
            "size_lines": summarize([p["size"] for p in human_window]),
            "releases_in_window": sum(1 for r in releases if since <= parse_ts(r["date"]) <= until),
            "individual": {
                "subject": subject,
                "accounts": subject_accounts,
                "merged_prs": len(mine),
                "cycle_hours": summarize([p["cycle_hours"] for p in mine]),
                "type_mix": {t: sum(1 for p in mine if p["type"] == t) for t in sorted({p["type"] for p in mine})},
                "reviews_given": sum(
                    1 for p in human_window for r in p["reviews"] if r["person"] == subject and p not in mine
                ),
                "active_days": len({p["merged_at"][:10] for p in mine}),
            },
        },
        "prs": prs,
        "releases": releases,
        "reverts": collect_reverts(),
        "skill_artifacts": collect_skill_artifacts(),
    }
    json.dump(output, sys.stdout, indent=2)
    print()


if __name__ == "__main__":
    main()
